# name: github pages

# on:
#   push:
#     branches:
#       - master  # Set a branch to deploy

# jobs:
#   deploy:
#     runs-on: ubuntu-18.04
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           submodules: recursive  # Fetch the Docsy theme
#           fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod

#       - name: Setup Node
#         uses: actions/setup-node@v1
#         with:
#           node-version: '12.x'

#       - name: Cache dependencies
#         uses: actions/cache@v1
#         with:
#           path: ~/.npm
#           key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#           restore-keys: |
#             ${{ runner.os }}-node-

#       - run: npm ci
#       - run: npm run build

#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_branch: gh-pages  # default: gh-pages

name: ci 
on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - gh-pages
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:  # mkdocs-blogging-plugin 给出的渲染问题解决方案
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: hexo cl && hexo d && hexo g